# Generated by Django 5.2.7 on 2025-10-13 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='899e1b84')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('desc', models.TextField(blank=True, max_length=600, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('subscriptions', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='autors/photos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='autors/banners/')),
                ('url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='f9f96a32')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=600)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('watch', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('url_photo', models.URLField(max_length=500)),
                ('url_video', models.URLField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='youtube.autor')),
            ],
        ),
    ]
