# Generated by Django 5.2.7 on 2025-10-26 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='0a49a34b')),
                ('avatar', models.URLField(max_length=500)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('desc', models.TextField(blank=True, max_length=600, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('subscriptions', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='autors/photos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='autors/banners/')),
                ('url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notificated_count', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='dd2341e6')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=600)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('watch', models.IntegerField(default=0)),
                ('url_photo', models.URLField(max_length=500)),
                ('url_video', models.URLField()),
                ('url_video_240', models.URLField(blank=True, null=True)),
                ('url_video_360', models.URLField(blank=True, null=True)),
                ('url_video_720', models.URLField(blank=True, null=True)),
                ('url_video_1080', models.URLField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='youtube.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
