# Generated by Django 5.2.7 on 2025-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_autor_slug_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='a99537c8'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='9bbba270'),
        ),
    ]
