# Generated by Django 5.2.7 on 2025-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_autor_slug_alter_video_slug_likesvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='0b7aeee8'),
        ),
        migrations.AlterField(
            model_name='likesvideo',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='d4f82e28'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='count_watch',
            field=models.IntegerField(default=0),
        ),
    ]
