# Generated by Django 5.2.7 on 2025-10-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_autor_slug_alter_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url_video',
        ),
        migrations.AddField(
            model_name='video',
            name='url_video_1080',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url_video_240',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url_video_480',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url_video_720',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='43aadbba'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='f89d32df'),
        ),
    ]
