# Generated by Django 5.2.7 on 2025-10-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_remove_video_url_video_video_url_video_1080_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='6559fce4'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='f1dba9f8'),
        ),
    ]
