# Generated by Django 5.2.7 on 2025-10-27 20:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_autor_slug_alter_likesvideo_count_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlater',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='likesvideo',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlater',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='97be0a48'),
        ),
        migrations.AlterField(
            model_name='notificated',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='98fe8dfa'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlater',
            unique_together={('user', 'video')},
        ),
    ]
