# Generated by Django 5.2.7 on 2025-10-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_video_url_video_alter_autor_slug_alter_video_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url_video',
            new_name='main_video',
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='23d72b34'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='ab171ce9'),
        ),
    ]
