# Generated by Django 5.2.7 on 2025-11-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_autor_slug_alter_video_slug_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='1bf76e95'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='access',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Unlisted'), (3, 'Private')], default=3),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='29c564cd'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='fe21ac6c'),
        ),
    ]
