# Generated by Django 5.2.7 on 2025-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_rename_url_video_video_main_video_alter_autor_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='main_video',
            new_name='url_video',
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='f9dda822'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='f41df9b6'),
        ),
    ]
