# Generated by Django 5.2.7 on 2025-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_rename_main_video_video_url_video_alter_autor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='b63a8e30'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='2686f0ac'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video',
            field=models.URLField(),
        ),
    ]
