# Generated by Django 5.2.7 on 2025-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_alter_autor_slug_alter_video_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url_video_480',
            new_name='url_video_360',
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='aa24afb4'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='a98445ef'),
        ),
    ]
