# Generated by Django 5.2.7 on 2025-11-02 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_alter_autor_slug_alter_playlist_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentsVideo',
            new_name='CommentsVideo',
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='cd9071fe'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='1e7cb743'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='3ea92a4b'),
        ),
    ]
