# Generated by Django 5.2.7 on 2025-11-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_rename_comentsvideo_commentsvideo_alter_autor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='6fbae021'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='f84bba3e'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='youtube.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='69de9e04'),
        ),
    ]
