# Generated by Django 5.2.7 on 2025-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_alter_autor_slug_alter_playlist_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='b43bf13d'),
        ),
        migrations.AlterField(
            model_name='commentsvideo',
            name='text',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='c7c704d3'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='2b3a65f2'),
        ),
    ]
