# Generated by Django 5.2.7 on 2025-11-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_alter_autor_slug_alter_commentsvideo_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='288b941f'),
        ),
        migrations.AlterField(
            model_name='commentsvideo',
            name='text',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='43c6d6ca'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='f3ca8686'),
        ),
    ]
