# Generated by Django 5.2.7 on 2025-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_alter_autor_slug_alter_commentsvideo_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsvideo',
            name='slug',
            field=models.SlugField(default='28b0f406'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(default='72bf72ee'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='df0f3d3a'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='a96ae693'),
        ),
    ]
