# Generated by Django 5.2.7 on 2025-11-02 18:08

import youtube.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_commentsvideo_slug_alter_autor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(blank=True, default=youtube.models.generate_random_slug, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commentsvideo',
            name='slug',
            field=models.SlugField(blank=True, default=youtube.models.generate_random_slug, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, default=youtube.models.generate_random_slug, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, default=youtube.models.generate_random_slug, null=True, unique=True),
        ),
    ]
