# Generated by Django 5.2.7 on 2025-11-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_alter_autor_slug_alter_commentsvideo_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsvideo',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='youtube.commentsvideo'),
        ),
    ]
