# Generated by Django 5.2.7 on 2025-11-03 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_alter_commentsvideo_reply_to_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='autor',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autor',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
