# Generated by Django 5.2.7 on 2025-11-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0017_remove_autor_subscribers_remove_autor_subscriptions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesСomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.commentsvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeu_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
