# Generated by Django 5.2.7 on 2025-11-07 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0018_likesсomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikesСomment',
            new_name='LikesComment',
        ),
    ]
